/* 
 * File:   mcal_interrupt_gen_cfg.h
 * Author: ADHAM KHALED
 *
 * Created on August 22, 2023, 8:15 PM
 */

#ifndef MCAL_INTERRUPT_GEN_CFG_H
#define	MCAL_INTERRUPT_GEN_CFG_H

#define INTERRUPT_FEATURE_ENABLE        1       
//#define INTERRUPT_PRIORITY_LEVELS_ENABLE    INTERRUPT_FEATURE_ENABLE
#define INTERRUPT_EXTERNAL_INTX_FEATURE_ENABLE   INTERRUPT_FEATURE_ENABLE
#define INTERRUPT_EXTERNAL_ONCHANGE_FEATURE_ENABLE   INTERRUPT_FEATURE_ENABLE

#endif	/* MCAL_INTERRUPT_GEN_CFG_H */

